on:
  push:
    tags: 'v*'

name: Create Release

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'
      - name: Build Project
        run: |
          yarn
          yarn build
          yarn package
      - name: Create Release
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

