on:
  push:
    tags: 'v*'

name: Create Release

jobs:
  build:
    name: Release to NPM
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'
      - name: Install Dependencies
        run: |
          yarn
      - name: Create Release
        run: |
          yarn config set npmAuthToken "$env:NPM_AUTH_TOKEN"
          yarn config set npmPublishRegistry "https://registry.npmjs.org"
          yarn publish --access public --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

