on:
  push:
    tags: 'v*'

name: Create Release

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.1.0'
      - name: Build Project
        run: |
          yarn
          yarn build
          yarn package
      - name: Create Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          gzip: false
          files: >
            release/chinese-convert-cli-linux
            release/chinese-convert-cli-macos
            release/chinese-convert-cli-win.exe
