on:
  push:
    tags: 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          access: 'public'
      - name: Create Github Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
