on:
  push:
    tags: 'v*'

name: Create Release

jobs:
  build:
    name: Release to NPM
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: yarn
      - name: Create Release
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

