on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'yarn'
      - name: Install Dependencies
        run: |
          yarn --immutable
      - name: Check Dependency Vulnerabilities
        run: |
          yarn npm audit
      - name: Run Lint
        run: |
          yarn lint
      - name: Build
        run: |
          yarn build
      - name: Unit Test
        run: |
          yarn test:unit
      - name: Integration Test
        run: |
          yarn test:integration
