on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [14, 16, 18]
    name: Test on node ${{ matrix.node }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: |
          pnpm i --frozen-lockfile
      - name: Check Dependency Vulnerabilities
        run: |
          pnpm audit
      - name: Run Lint
        run: |
          pnpm lint
      - name: Build
        run: |
          pnpm build
      - name: Unit Test
        run: |
          pnpm test:unit
      - name: Integration Test
        run: |
          pnpm test:integration
