on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.4'
      - name: Install Dependencies
        run: |
          yarn
      - name: Check Dependency Vulnerabilities
        run: |
          yarn audit
      - name: Run Lint
        run: |
          yarn lint
      - name: Build
        run: |
          yarn build
      - name: Unit Test
        run: |
          yarn test:unit
      - name: Integration Test
        run: |
          yarn test:integration
